<a href="https://colab.research.google.com/github/MarioViniciusBC/NumPy/blob/main/pandas_loc_iloc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

### `.loc` e `.iloc`

Para dominar a seleção e filtragem de dados no Pandas, é essencial compreender a diferença fundamental entre os métodos `.loc` e `.iloc`. O `.loc` é baseado nos rótulos (labels), o que significa que ele busca os dados utilizando o índice explícito (o "nome" que você deu para as linhas) e os nomes das colunas. Por outro lado, o `.iloc` é baseado na posição numérica (integers), funcionando de forma idêntica às listas tradicionais do Python: a busca é feita pelas coordenadas implícitas (0, 1, 2...), independentemente de como as linhas e colunas foram nomeadas. Em resumo: use o `.loc` quando quiser buscar a informação pelo seu nome, e o `.iloc` quando precisar encontrá-la pela sua posição exata na tabela.

Ambos os comandos servem para selecionar linhas e colunas em um DataFrame. A diferença está na forma como eles fazem isso.
* **loc**: Usa o **nome** (rótulo/label) da linha e da coluna.
* **iloc**: Usa a **posição numérica** (índice/integer) da linha e coluna (indexado a partir do 0).

In [ ]:
import pandas as pd

In [ ]:
dados = {
    'Nome': ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'Idade': [25, 30, 22, 28],
    'Cidade': ['Rio', 'São Paulo', 'Belo Horizonte', 'Curitiba']
}

In [ ]:
# Criando o DataFrame com índices (nomes das linhas) personalizados
df = pd.DataFrame(dados, index=['A', 'B', 'C', 'D'])
df

     Nome  Idade          Cidade
A     Ana     25             Rio
B   Bruno     30       São Paulo
C  Carlos     22  Belo Horizonte
D   Diana     28        Curitiba

#### **loc**

O atributo `loc` permite indexação e fatiamento que sempre referenciam o índice explícito. Com o `loc`, você precisa usar o nome exato que está no índice da linha e o nome da coluna. A sintaxe é sempre `df.loc[linha, coluna]`.

Por exemplo, para pegar um valor específico como a idade do Bruno (que está na linha 'B' e coluna 'Idade'):

In [ ]:
# Sintaxe: df.loc[linha, coluna]
idade_bruno = df.loc['B', 'Idade']
print(idade_bruno)

30

In [ ]:
# Pegando todos os dados da linha 'A'
df.loc['A'] # Passa só o rótulo da linha

Nome      Ana
Idade      25
Cidade    Rio
Name: A, dtype: object

Caso precisemos selecionar múltiplas linhas e colunas, podemos passar listas:

In [ ]:
# # Sintaxe: df.loc[linha, coluna]
df.loc[['A', 'C'], ['Nome', 'Cidade']]

     Nome          Cidade
A     Ana             Rio
C  Carlos  Belo Horizonte

Essa é uma ótima estratégia para selecionar linhas específicas e "soltas" (que não estão em sequência). Podemos somente passar a lista de linhas que queremos selecionar:

In [ ]:
# Retorna apenas as linhas 'A' e 'C'
df.loc[['A', 'C']]

     Nome  Idade          Cidade
A     Ana     25             Rio
C  Carlos     22  Belo Horizonte

Note que você usará dois pares de colchetes: o primeiro é do próprio comando loc e o segundo é a lista de linhas.

Se você quer pegar um "bloco" de linhas que estão juntas uma da outra, você não precisa de uma lista. Você pode usar os dois pontos `:` para indicar o intervalo (do início até o fim).

In [ ]:
# Retorna as linhas 'A', 'B' e 'C'
df.loc['A':'B']

    Nome  Idade     Cidade
A    Ana     25        Rio
B  Bruno     30  São Paulo

Regra para os colchetes no **loc**:
* `df.loc['A']`: Retorna uma única linha (formato Series).

* `df.loc[['A', 'C']]`: Retorna múltiplas linhas específicas (exige a lista interna, retorna formato DataFrame).

### Exemplo:

In [ ]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [ ]:
'a' in data

True

Em uma Series do Pandas, o comando `data.keys()` retorna o índice (index) daquela Series:

In [ ]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

O comando `data.keys()` faz exatamente a mesma coisa que o comando `data.index`.

Na prática e no dia a dia da programação com Pandas, é muito mais comum e idiomático usar `data.index` quando queremos acessar os rótulos de uma Series. O método `.keys()` existe mais por uma questão de compatibilidade com a forma como os dicionários nativos do Python funcionam.

#### **iloc**

Com o `iloc` (o "i" vem de integer ou inteiro), você ignora os nomes que deu para as linhas ou colunas e usa apenas a ordem numérica delas. A primeira linha é 0, a segunda é 1, a primeira coluna é 0, e assim por diante. A sintaxe é `df.iloc[posição_linha, posição_coluna]`.

Vamos pegar a idade do Bruno com o comando `iloc`:

In [ ]:
idade_bruno_2 = df.iloc[1, 1]
print(idade_bruno_2)

30

### **Exemplo: Base de dados Risco Crédito**

In [ ]:
# Carregamento da base de dados
dados = pd.read_csv('/content/credit_data.csv')

In [ ]:
dados.loc[dados['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

### **Resumo das Diferenças**

| Característica | `loc` (Label-based) | `iloc` (Integer-based) |
| :--- | :--- | :--- |
| **Referência** | Nomes (rótulos) das linhas e colunas | Posição numérica (0, 1, 2...) |
| **Sintaxe base** | `df.loc['nome_linha', 'nome_coluna']` | `df.iloc[num_linha, num_coluna]` |
| **Fatiamento (Slicing)**| **Inclui** o último item (`'A':'C'` pega A, B e C) | **Exclui** o último item (`0:2` pega 0 e 1) |
| **Aceita Condições?** | Sim (ex: `df.loc[df['Idade'] > 25]`) | Não diretamente (precisa converter para array/lista) |

### **Índices explícitos e implícitos**

Quando trabalhamos com uma Series no Pandas, é fundamental entender que, por baixo dos panos, toda Series possui dois índices funcionando ao mesmo tempo: um **explícito** e outro **implícito**.
* O **índice explícito** é aquele que você dá nome. Ele é o rótulo oficial daquele dado. Pode ser uma letra, uma palavra (string), uma data ou até mesmo um número que você escolheu.

* O **índice implícito** é a posição numérica (coordenada) do dado na memória do Python. Ele é "secreto" e funciona sempre do mesmo jeito: a primeira linha é sempre a 0, a segunda é a 1, a terceira é a 2, e assim por diante. Você não pode alterar o índice implícito, ele é a ordem natural dos dados.

No exemplo a seguir, definimos uma Series:

In [ ]:
data = pd.Series(['Mario', 'Polly', 'Jorel'],
                 index=['w', 'e', 'p'])
data

w    Mario
e    Polly
p    Jorel
dtype: object

No exemplo acima, está fácil verificar quais são os índices explícitos. A seguir, podemos verificar como acessar um elemento passando um índice explícito:

In [ ]:
# Indexação com índice explícito 'w'
data['w']

'Mario'

In [ ]:
# Indexação com índice implícito 0
data[0]

/tmp/ipykernel_808/460267674.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[0]

'Mario'

* **FutureWarning**: O uso de colchetes simples (`[]` - que o Python chama de `__getitem__`) para buscar posições numéricas está obsoleto e vai deixar de funcionar. Em uma versão futura do Pandas, se você colocar um número entre colchetes (ex: `serie[1]`), nós vamos sempre procurar pelo índice explícito (o rótulo/nome da linha), e não mais pela posição.

Vejamos agora o próximo exemplo:

In [ ]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [ ]:
# índice explícito ao indexar
data[1]

'a'

In [ ]:
# índice implícito ao fatiar
data[1:3]

3    b
5    c
dtype: object

Um princípio orientador do código Python é que "explícito é melhor que implícito". A natureza explícita de **loc** e **iloc** os torna muito úteis para manter o código limpo e legível; especialmente no caso de índices inteiros, recomendo usar ambos para tornar o código mais fácil de ler e entender, e para evitar bugs sutis devido à convenção mista de indexação/fatiamento.